### ISSUE TITLE
Error: write EPIPE

### ISSUE THREAD

**Issue by aderbas** [hajareshyam/pdf-creator-node#55] opened 2021-10-20 17:51 UTC
Sorry if anyone has had this problem and it has been fixed, I have not found it. I'm trying to run the basic example documentation in the application's Docker container.

Below is my Dockerfile and the error.

```
# Dockerizing project

FROM node:14-alpine

# Service port
ARG PORT

RUN apk add --no-cache msttcorefonts-installer fontconfig
RUN update-ms-fonts

# Create app directory
RUN mkdir -p /home/node/app/node_modules && chown -R node:node /home/node/app
WORKDIR /home/node/app

# Copy package.json
COPY package*.json ./

# Install dependencies
RUN npm install

# App source
COPY . .

# Change onwner to node user
RUN chown -R node:node /home/node/app

# Chanhe user to node user
USER node

# Bind port
EXPOSE $PORT

CMD ["npm", "start"]
```

I get this error:
```javascript
events.js:292
      throw er; // Unhandled 'error' event
      ^

Error: write EPIPE
    at afterWriteDispatched (internal/stream_base_commons.js:156:25)
    at writeGeneric (internal/stream_base_commons.js:147:3)
    at Socket._writeGeneric (net.js:785:11)
    at Socket._write (net.js:797:8)
    at writeOrBuffer (internal/streams/writable.js:358:12)
    at Socket.Writable.write (internal/streams/writable.js:303:10)
    at PDF.PdfExec [as exec] (/home/node/app/node_modules/html-pdf/lib/pdf.js:156:15)
    at PDF.PdfToFile [as toFile] (/home/node/app/node_modules/html-pdf/lib/pdf.js:85:8)
    at /home/node/app/node_modules/pdf-creator-node/index.js:42:20
    at new Promise (<anonymous>)
Emitted 'error' event on Socket instance at:
    at emitErrorNT (internal/streams/destroy.js:106:8)
    at emitErrorCloseNT (internal/streams/destroy.js:74:3)
    at processTicksAndRejections (internal/process/task_queues.js:80:21) {
  errno: -32,
  code: 'EPIPE',
  syscall: 'write'
}
```
On my machine it works perfectly. Only in the container that generates the error. Anyone to help? Appreciate.

**Comment by aderbas** [comment] 2021-11-10 11:58
Thanks for the answer. The same error `Error: write EPIPE`
=/

**Comment by duncanmapes** [comment] 2022-01-18 13:39
this is happening to me on Lambda too, runtime `nodejs14.x`

**Comment by FZampetti** [comment] 2022-02-14 10:11
I have the same issue, has anyone fixed it?

**Comment by xixxdev** [comment] 2022-03-21 15:41
> nodejs/node#40553

Have you fixed that issue?

**Comment by xixxdev** [comment] 2022-03-21 15:50
+, has anyone fixed it?

**Comment by EstebanCardenas14** [comment] 2022-05-01 07:47
hi, had the same problem
I solved it by declaring the path of the phantomjs.

when i said "project_name" is the name of the project where you develop
i opened the folder node_modules and review if exist the phantomjs folder, opened the most simillar folder "phantomjs-prebuilt", go to bin and in this point you see a file with the name phantomjs, this is the route

`const options = {
            phantomPath: "../<project_name>/node_modules/phantomjs-prebuilt/bin/phantomjs",
            format: "A3",
            marginTop: '0.5in',
            border: '0.25in',
        };`

**Comment by vitorfreitas** [comment] 2022-05-28 14:59
For me, moving from `node:14-alpine` to `node:14` solved the problem. Probably the alpine image misses some dependencies required for this library to work.

**Comment by hajareshyam** [comment] 2022-08-03 19:48
I think this is image related issue. Closing the defect.

**Closed by hajareshyam** 2022-08-03 19:48 UTC

**Comment by EstebanCardenas14** [comment] 2022-09-20 14:29
maybe if you are in nodejs do the command "npm rebuild", sometimes the dependencies are wrong, "rebuild" fixes it

**Comment by AYOUBBASIDI** [comment] 2023-01-16 10:10
I'm facing the same error , It works fine locally , but when I've containerized the app in the docker the error appears. 
Has anyone fixed it?

**Comment by nelsoncv** [comment] 2023-04-10 03:58
Im facing same issue on RHEL 8.7, tried set the phantomPath too. No issue running on local macbook.


node:events:491
      throw er; // Unhandled 'error' event
      ^

Error: write EPIPE
    at WriteWrap.onWriteComplete [as oncomplete] (node:internal/stream_base_commons:94:16)
Emitted 'error' event on Socket instance at:
    at emitErrorNT (node:internal/streams/destroy:151:8)
    at emitErrorCloseNT (node:internal/streams/destroy:116:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
  errno: -32,
  code: 'EPIPE',
  syscall: 'write'
}

**Comment by nelsoncv** [comment] 2023-04-10 08:40
Found solution elsewhere on other package that uses phantomjs, the issue is i ran on local and sync node_modules to servers(due to server has no internet access). So a rebuild is required.

`npm rebuild phantomjs-prebuilt`

**Comment by kaljonwal** [comment] 2023-12-07 08:49
2023-12-07T08:46:54.243Z	676a6d2e-3e26-4198-9829-315d350e1ced	ERROR	Uncaught Exception 	{
    "errorType": "Error",
    "errorMessage": "write EPIPE",
    "code": "EPIPE",
    "errno": "EPIPE",
    "syscall": "write",
    "stack": [
        "Error: write EPIPE",
        "    at WriteWrap.onWriteComplete [as oncomplete] (internal/stream_base_commons.js:94:16)"
    ]
}

i'm getting this error
base image
public.ecr.aws/lambda/nodejs:20
